// <auto-generated />
using System;
using BusinessObject.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BusinessObject.Migrations
{
    [DbContext(typeof(ConnectDB))]
    [Migration("20240815151017_DBInit")]
    partial class DBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BusinessObject.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("Status")
                        .HasColumnType("bit");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Warning")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("BusinessObject.Model.AccountDetail", b =>
                {
                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Avatar")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("BacksideCCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("District")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FrontCCCD")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Phone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Ward")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AccountID");

                    b.ToTable("AccountDetails");
                });

            modelBuilder.Entity("BusinessObject.Model.AuctioneerDetail", b =>
                {
                    b.Property<int>("ListAuctioneerID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<string>("EndDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EndTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberofAuctionRounds")
                        .HasColumnType("int");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("PriceStep")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("StartDay")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StartTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TimePerLap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ListAuctioneerID");

                    b.HasIndex("CategoryID");

                    b.ToTable("AuctioneerDetail");
                });

            modelBuilder.Entity("BusinessObject.Model.Bet", b =>
                {
                    b.Property<int>("BetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BetID"));

                    b.Property<decimal>("PriceBit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RAID")
                        .HasColumnType("int");

                    b.HasKey("BetID");

                    b.HasIndex("RAID");

                    b.ToTable("Bet");
                });

            modelBuilder.Entity("BusinessObject.Model.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("NameCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryID");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("BusinessObject.Model.Feedback", b =>
                {
                    b.Property<int>("RAID")
                        .HasColumnType("int");

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SatisfactionLevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RAID");

                    b.HasIndex("AccountID");

                    b.ToTable("Feedback");
                });

            modelBuilder.Entity("BusinessObject.Model.FileAttachments", b =>
                {
                    b.Property<int>("FileAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FileAID"));

                    b.Property<string>("FileAuctioneer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ListAuctioneerID")
                        .HasColumnType("int");

                    b.Property<string>("SignatureImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FileAID");

                    b.HasIndex("ListAuctioneerID");

                    b.ToTable("FileAttachments");
                });

            modelBuilder.Entity("BusinessObject.Model.ListAuctioneer", b =>
                {
                    b.Property<int>("ListAuctioneerID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ListAuctioneerID"));

                    b.Property<int?>("Creator")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Manager")
                        .HasColumnType("int");

                    b.Property<string>("NameAuctioneer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("StartingPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool?>("StatusAuction")
                        .HasColumnType("bit");

                    b.HasKey("ListAuctioneerID");

                    b.HasIndex("Creator");

                    b.HasIndex("Manager");

                    b.ToTable("ListAuctioneer");
                });

            modelBuilder.Entity("BusinessObject.Model.Notification", b =>
                {
                    b.Property<int>("NoticationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NoticationID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NoticationID");

                    b.HasIndex("AccountID");

                    b.ToTable("Notications");
                });

            modelBuilder.Entity("BusinessObject.Model.Payment", b =>
                {
                    b.Property<int>("PayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayID"));

                    b.Property<string>("PaymentDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RAID")
                        .HasColumnType("int");

                    b.HasKey("PayID");

                    b.HasIndex("RAID");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("BusinessObject.Model.RegistAuctioneer", b =>
                {
                    b.Property<int>("RAID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RAID"));

                    b.Property<int>("AccountID")
                        .HasColumnType("int");

                    b.Property<bool?>("AuctionStatus")
                        .HasColumnType("bit");

                    b.Property<int>("ListAuctioneerID")
                        .HasColumnType("int");

                    b.Property<string>("PaymentTerm")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RAID");

                    b.HasIndex("AccountID");

                    b.HasIndex("ListAuctioneerID");

                    b.ToTable("RegistAuctioneer");
                });

            modelBuilder.Entity("BusinessObject.Model.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BusinessObject.Model.TImage", b =>
                {
                    b.Property<int>("TImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TImageId"));

                    b.Property<int>("FileAID")
                        .HasColumnType("int");

                    b.Property<string>("Imange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TImageId");

                    b.HasIndex("FileAID");

                    b.ToTable("TImage");
                });

            modelBuilder.Entity("BusinessObject.Model.Account", b =>
                {
                    b.HasOne("BusinessObject.Model.Role", "Role")
                        .WithMany("Accounts")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("BusinessObject.Model.AccountDetail", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Account")
                        .WithOne("AccountDetail")
                        .HasForeignKey("BusinessObject.Model.AccountDetail", "AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("BusinessObject.Model.AuctioneerDetail", b =>
                {
                    b.HasOne("BusinessObject.Model.Category", "Categorys")
                        .WithMany("AuctioneerDetails")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.ListAuctioneer", "ListAuctioneers")
                        .WithOne("AuctioneerDetails")
                        .HasForeignKey("BusinessObject.Model.AuctioneerDetail", "ListAuctioneerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorys");

                    b.Navigation("ListAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.Bet", b =>
                {
                    b.HasOne("BusinessObject.Model.RegistAuctioneer", "RegistAuctioneer")
                        .WithMany("Bets")
                        .HasForeignKey("RAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RegistAuctioneer");
                });

            modelBuilder.Entity("BusinessObject.Model.Feedback", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Accounts")
                        .WithMany("Feedbacks")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.RegistAuctioneer", "RegistAuctioneers")
                        .WithOne("Feedbacks")
                        .HasForeignKey("BusinessObject.Model.Feedback", "RAID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("RegistAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.FileAttachments", b =>
                {
                    b.HasOne("BusinessObject.Model.AuctioneerDetail", "AuctioneerDetails")
                        .WithMany("FileAttachments")
                        .HasForeignKey("ListAuctioneerID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("AuctioneerDetails");
                });

            modelBuilder.Entity("BusinessObject.Model.ListAuctioneer", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "CreatorAccount")
                        .WithMany("CreatedAuctioneers")
                        .HasForeignKey("Creator")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("BusinessObject.Model.Account", "ManagerAccount")
                        .WithMany("ManagedAuctioneers")
                        .HasForeignKey("Manager")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("CreatorAccount");

                    b.Navigation("ManagerAccount");
                });

            modelBuilder.Entity("BusinessObject.Model.Notification", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Accounts")
                        .WithMany("Notifications")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("BusinessObject.Model.Payment", b =>
                {
                    b.HasOne("BusinessObject.Model.RegistAuctioneer", "RegistAuctioneers")
                        .WithMany("Payments")
                        .HasForeignKey("RAID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("RegistAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.RegistAuctioneer", b =>
                {
                    b.HasOne("BusinessObject.Model.Account", "Accounts")
                        .WithMany("RegistAuctioneers")
                        .HasForeignKey("AccountID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BusinessObject.Model.ListAuctioneer", "ListAuctioneers")
                        .WithMany("RegistAuctioneers")
                        .HasForeignKey("ListAuctioneerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Accounts");

                    b.Navigation("ListAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.TImage", b =>
                {
                    b.HasOne("BusinessObject.Model.FileAttachments", "FileAttachments")
                        .WithMany("TImages")
                        .HasForeignKey("FileAID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileAttachments");
                });

            modelBuilder.Entity("BusinessObject.Model.Account", b =>
                {
                    b.Navigation("AccountDetail")
                        .IsRequired();

                    b.Navigation("CreatedAuctioneers");

                    b.Navigation("Feedbacks");

                    b.Navigation("ManagedAuctioneers");

                    b.Navigation("Notifications");

                    b.Navigation("RegistAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.AuctioneerDetail", b =>
                {
                    b.Navigation("FileAttachments");
                });

            modelBuilder.Entity("BusinessObject.Model.Category", b =>
                {
                    b.Navigation("AuctioneerDetails");
                });

            modelBuilder.Entity("BusinessObject.Model.FileAttachments", b =>
                {
                    b.Navigation("TImages");
                });

            modelBuilder.Entity("BusinessObject.Model.ListAuctioneer", b =>
                {
                    b.Navigation("AuctioneerDetails")
                        .IsRequired();

                    b.Navigation("RegistAuctioneers");
                });

            modelBuilder.Entity("BusinessObject.Model.RegistAuctioneer", b =>
                {
                    b.Navigation("Bets");

                    b.Navigation("Feedbacks")
                        .IsRequired();

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("BusinessObject.Model.Role", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
